# GitHub Actions workflow for testing and continuous integration.
#
# This file performs testing using tox and tox.ini to define and configure the test environments.

name: CI Tests

on:
  schedule:
    # run every Wednesday at 6am UTC
    - cron: '0 6 * * 3'
  push:
    branches:
      - main
    tags:
    - '*'
  pull_request:
     branches: # only build on PRs against 'main' if you need to further limit when CI is run.
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Github Actions supports ubuntu, windows, and macos virtual environments:
  # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
  ci_tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@22ddf09dfabb443adddfb9f861b7d41a787d6b1a  # v3.0.3
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      submodules: false
      coverage: ''
      default_python: '3.14'
      envs: |
        - name: Code style checks
          linux: codestyle

        - name: Link checks
          linux: linkcheck

        - name: Python 3.12 with base dependencies
          linux: py312-test

        - name: Python 3.13 with base dependencies
          linux: py313-test

        - name: Python 3.12 with oldest version of key dependencies
          linux: py312-test-oldestdeps

        - name: OS X - Python 3.14 with base dependencies
          macos: py314-test

        - name: Windows - Python 3.14 with base dependencies
          windows: py314-test

        - name: Python 3.14 with remote data, all dependencies, and coverage
          linux: py314-test-alldeps-cov
          toxargs: -v
          posargs: --remote-data=any
          coverage: codecov

  allowed_failures:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@22ddf09dfabb443adddfb9f861b7d41a787d6b1a  # v3.0.3
    with:
      submodules: false
      coverage: ''
      default_python: '3.14'
      envs: |
        - name: (Allowed Failure) Python 3.14 with remote data and latest dev versions of key dependencies
          linux: py314-test-devdeps
          posargs: --remote-data=any --verbose
